### ISSUE TITLE
Provisioning only works with a reload --provision

### ISSUE THREAD

**Issue by bdgeorge** [mhahn/vagrant-librarian-puppet#24] opened 2014-11-11 10:29 UTC
I'm hitting a problem with the following error message when provisioning with puppet librarian
```
Shared folders that Puppet requires are missing on the virtual machine.
This is usually due to configuration changing after already booting the
machine. The fix is to run a `vagrant reload` so that the proper shared
folders will be prepared and mounted on the VM.
```
I only get this error on machines using this plugin, so as I'm not sure if the problem is with Vagrant or the plugin I'm cross posting this issue from the vagrant issue list! 

Full details here: https://github.com/mitchellh/vagrant/issues/4810

**Comment by mhahn** [comment] 2015-01-13 16:35
are you still having this issue?

**Comment by bdgeorge** [comment] 2015-01-14 09:37
I am - just upgraded Vagrant to 1.7.2 as #4810 suggested that it was fixed, but still getting the same problem.

**Comment by fnordfish** [comment] 2015-01-21 23:01
@bdgeorge : can you please try running `librarian-puppet config rsync true --global`

**Comment by jhoblitt** [comment] 2015-10-15 15:09
@bdgeorge I'm unable to reproduce this on vagrant 1.7.4 with any of the virtualbox, aws, or digital_ocean providers.  I'm going to close this issue since it sounds vagrant core/provider related.  If your still experiencing it, please provide a working `Vagrantfile` that can reproduce the failure.

**Closed by jhoblitt** 2015-10-15 15:09 UTC
